CREATE TABLE IF NOT EXISTS SPONSOR(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250),
    industry VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS EVENT(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250),
    date VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS EVENT_SPONSOR(
    eventId INT,
    sponsorId INT,
    PRIMARY KEY(eventId, sponsorId),
    FOREIGN KEY(eventId) REFERENCES EVENT(id),
    FOREIGN KEY(sponsorId) REFERENCES SPONSOR(id)
);