CREATE TABLE IF NOT EXISTS WRITER(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250),
    bio VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS MAGAZINE(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(250),
    publicationDate VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS WRITER_MAGAZINE(
    writerId INT,
    magazineId INT,
    PRIMARY KEY(writerId, magazineId),
    FOREIGN KEY(writerId) REFERENCES WRITER(id),
    FOREIGN KEY(magazineId) REFERENCES MAGAZINE(id)
);