CREATE TABLE IF NOT EXISTS CATEGORY(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250),
    description VARCHAR(250)
);


CREATE TABLE IF NOT EXISTS PRODUCT(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(250),
    description VARCHAR(250),
    price DOUBLE,
    categoryId INT,
    FOREIGN KEY(categoryId) REFERENCES CATEGORY(id) ON DELETE CASCADE
);