CREATE TABLE IF NOT EXISTS RESEARCHER(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    specialization VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS PROJECT(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    budget DOUBLE
);


CREATE TABLE IF NOT EXISTS RESEARCHER_PROJECT(
    researcherId INT,
    projectId INT,
    PRIMARY KEY(researcherId, projectId),
    FOREIGN KEY(researcherId) REFERENCES RESEARCHER(id),
    FOREIGN KEY(projectId) REFERENCES PROJECT(id)
);