CREATE TABLE IF NOT EXISTS ARTIST(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150),
    genre VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS ART(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(150),
    theme VARCHAR(150),
    artistId INT,
    FOREIGN KEY(artistId) REFERENCES ARTIST(id)
);

CREATE TABLE IF NOT EXISTS GALLERY(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150),
    location VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS ARTIST_GALLERY(
    artistId INT,
    galleryId INT,
    PRIMARY KEY(artistId, galleryId),
    FOREIGN KEY(artistId) REFERENCES ARTIST(id),
    FOREIGN KEY(galleryId) REFERENCES GALLERY(id)
);